name: Auto PR create

on:
  push:
    branches:    
      - 'feature/jenkins-ci2'
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature/jenkins-ci2
          base: main
