name: Auto PR create

on:
  push:
    branches:    
      - 'feature/jenkins-ci2'
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        ref: feature/jenkins-ci2
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: feature/jenkins-ci2
