name: Auto create pr and merge

on:
  push:
    branches:    
      - 'feature/jenkins-ci2'
jobs:
  create_pull_request_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: create pull request
        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: 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
        run: gh pr create --repo https://github.com/tmonj1/self-hosted-runner-test3 --title autocommit -B main -H feature/jenkins-ci2 -b autocreatedpr
      - name: merge PR
        env:
          GH_TOKEN: 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
        run: git config --local user.email tmj@gmail.com && git config --local user.name tmj && gh pr review --repo https://github.com/tmonj1/self-hosted-runner-test3 --approve feature/jenkins-ci2 && \
             gh pr merge --repo https://github.com/tmonj1/self-hosted-runner-test3 --merge feature/jenkins-ci2
