name: Auto create pr and merge using self-hosted runner

on:
  push:
    branches:    
      - 'feature/b'
jobs:
  create_pull_request_and_merge:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: create pull request
        id: cpr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url=$( gh pr create --repo https://github.com/tmonj1/self-hosted-runner-test3 --title autocreatepr -B main -H feature/b -b autocreatedpr )
          echo "::set-output name=pr_url::$pr_url"
#      - name: review PR
#        id: rpr
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh pr review --repo https://github.com/tmonj1/self-hosted-runner-test3 --approve feature/b
      - name: merge PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TMJ }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pr_url }} -m --admin --repo https://github.com/tmonj1/self-hosted-runner-test3
